### ISSUE TITLE
flutter run fails when running example on ios

### ISSUE THREAD

**Issue by lotux** [Piasy/FlutterWebRTCDataChannel#1]
flutter run seems to look for Runner.xcodeproj but it doesn't exist in example directory, probably you forgot to commit?

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /[REDACTED]/sandbox/FlutterWebRTCDataChannel/example/ios/Runner.xcodeproj -target Runner -showBuildSettings

**Comment by Piasy** [comment]
Please read README: https://github.com/Piasy/FlutterWebRTCDataChannel#development-setup
