### ISSUE TITLE
Dependency problem on Android

### ISSUE THREAD

**Issue by OscarLinnarsson** [Piasy/FlutterWebRTCDataChannel#2]
First of all, I really like this plugin!!

I’ve got it to work on iOS devices but I can’t seem to find a solution to this error 

**What went wrong:
A problem occurred evaluating root project 'android'.
Could not find method api() for arguments [org.webrtc:google-webrtc:1.0.22672] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.**

caused by  

**dependencies {
    api 'org.webrtc:google-webrtc:1.0.22672'
}**

in project/android/build.gradle.

**Comment by OscarLinnarsson** [comment]
Many thanks in advance!!

**Comment by Piasy** [comment]
@OscarLinnarsson It seems you are using an old version of gradle android plugin, you can try to replace `api` with `compile`.
