### ISSUE TITLE
Many connections at once

### ISSUE THREAD

**Issue by OscarLinnarsson** [Piasy/FlutterWebRTCDataChannel#3]
First of all I want to say a huge thank you for this great plug-in! 

As I was trying to create a group chat using this plug-in I first realized that a room is full when two peers have entered it. To create the group chat my next solution was to let one device be the host and brodcast all incomming messages to then realize that one device is limited to only keeping one connection at once.

Depending on what is easiest to implement, multiple peers in the same room or multiple p2p connections at once on the same device, that solution would be sufficient.

Many tanks in advance!!

**Comment by Piasy** [comment]
The two peers limitation is determined by the apprtc server. Actually this
plugin is a very basic demonstration, it use signaling code from the
official demo, to use it in production, bunch of work is needed.

Sorry for the late response,  I'm on vocation these two weeks.

Best regards.
此致，祝好！
-------------------------------------------------------
Piasy Xu
许建林
-------------------------------------------------------
<https://github.com/Piasy>

<https://www.linkedin.com/in/piasy>

**Comment by OscarLinnarsson** [comment]
Ahh, ok, good to know. Then I'll continue browsing for a good plugin as I'm not to familiar with how to implement these protocols.

Best regards and sorry for the delayed response.
